### ISSUE TITLE
health go fail when add chain

### ISSUE THREAD

**Issue by Amirioelmos** [hyperledger/cello#107]
hello,

when i add new chain in added host (for example host1 by docker), 

cello-watchdog        | [2020-02-04 16:04:52,940] INFO [modules.cluster] [cluster.py:900        db_update_one()] - filter {'id': '96c93fc42a0448768d732f44b211feaa', 'state': 'active'} operations {'health': 'FAIL'}                                                                                             

why?
thanks.

**Comment by xiegangqingnian** [comment]
你好，请问你已经部署好整个cello项目了吗
