### ISSUE TITLE
wget: bad address 'nexus.hyperledger.org'

### ISSUE THREAD

**Issue by djraj** [hyperledger/cello#109]
## Expected Behavior

`make docker` should work.

## Current Behavior

Upon running `make docker`, it fails at getting the address "nexus.hyperledger.org"
![image](https://user-images.githubusercontent.com/34974605/74314691-d7e65200-4db0-11ea-8f9d-7cf285d15831.png)

## Possible Solution

"nexus.hyperledger.or" has been retired. Check this [link](https://lists.hyperledger.org/g/fabric/topic/hyperledger_nexus_repository/70049382?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,70049382) for proof.

Artifacts have been moved to [JFrog](https://hyperledger.jfrog.io/hyperledger/webapp/#/home)

Possible solution is to update the links that points to the correct repo.

## Context (Environment)

* OS: Ubuntu Linux 16.04
* Architecture: x64
* Docker version: 18.06.1-ce
* Docker compose version: 1.24.1

**Comment by yeasy** [comment]
@djraj , thanks for reporting the issue.
