### ISSUE TITLE
How do I add nodes?

### ISSUE THREAD

**Issue by zhaixuepan** [hyperledger/cello#111]
![image](https://user-images.githubusercontent.com/15258081/75240046-ad5bb680-57fe-11ea-8dc4-d25e7525500b.png)

**Comment by qutubdahodwala** [comment]
I believe you are logged in using the default user account is an 'operator' which can't create nodes. 
You need to register an 'Agent' first, create an organisation and then a user 'administrator' under that organisation. The administrator user can then add nodes using the agent.

However, I might be wrong, as my understanding of the flow is based on me playing around with cello and I haven't actually looked into the source code (and there are no docs for the latest version).
