### ISSUE TITLE
 cello-user-dashboard 意外终止

### ISSUE THREAD

**Issue by xiegangqingnian** [hyperledger/cello#112]
cello-user-dashboard  | 2020-02-26 02:45:19,512 INFO 124 [egg-multipart] stream mode enable
cello-user-dashboard  | /node_modules/egg/lib/application.js:70
cello-user-dashboard  |       throw e;
cello-user-dashboard  |       ^
cello-user-dashboard  | 
cello-user-dashboard  | AssertionError [ERR_ASSERTION]: [egg-passport-oauth2] config.passportOauth2.key required
cello-user-dashboard  |     at module.exports.app (/node_modules/egg-passport-oauth2/app.js:10:3)
cello-user-dashboard  |     at Hook.configDidLoad (/node_modules/egg-core/lib/lifecycle.js:92:9)
cello-user-dashboard  |     at Lifecycle.triggerConfigDidLoad (/node_modules/egg-core/lib/lifecycle.js:143:14)
cello-user-dashboard  |     at Lifecycle.triggerConfigWillLoad (/node_modules/egg-core/lib/lifecycle.js:137:10)
cello-user-dashboard  |     at AppWorkerLoader.loadCustomApp (/node_modules/egg-core/lib/loader/mixin/custom.js:37:20)
cello-user-dashboard  |     at AppWorkerLoader.load (/node_modules/egg/lib/loader/app_worker_loader.js:33:10)
cello-user-dashboard  |     at new Application (/node_modules/egg/lib/application.js:66:19)
cello-user-dashboard  |     at Object.<anonymous> (/node_modules/egg-cluster/lib/app_worker.js:19:13)
cello-user-dashboard  |     at Module._compile (module.js:643:30)
cello-user-dashboard  |     at Object.Module._extensions..js (module.js:654:10)
cello-user-dashboard  | [2020-02-26 02:45:19.532] [cfork:master:108] worker:124 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false, worker.disableRefork: true)
cello-user-dashboard  | [2020-02-26 02:45:19.533] [cfork:master:108] don't fork, because worker:124 will be kill soon
cello-user-dashboard  | 2020-02-26 02:45:19,533 INFO 108 [master] app_worker#1:124 disconnect, suicide: false, state: disconnected, current workers: ["1"]
cello-user-dashboard  | [2020-02-26 02:45:19.537] [cfork:master:108] worker:124 exit (code: 1, exitedAfterDisconnect: false, state: dead, isDead: true, isExpected: false, worker.disableRefork: true)
cello-user-dashboard  | 2020-02-26 02:45:19,539 ERROR 108 nodejs.AppWorkerDiedError: [master] app_worker#1:124 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
cello-user-dashboard  |     at Master.onAppExit (/node_modules/egg-cluster/lib/master.js:408:21)
cello-user-dashboard  |     at emitOne (events.js:116:13)
cello-user-dashboard  |     at Master.emit (events.js:211:7)
cello-user-dashboard  |     at Messenger.sendToMaster (/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
cello-user-dashboard  |     at Messenger.send (/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
cello-user-dashboard  |     at EventEmitter.cluster.on (/node_modules/egg-cluster/lib/master.js:277:22)
cello-user-dashboard  |     at emitThree (events.js:141:20)
cello-user-dashboard  |     at EventEmitter.emit (events.js:217:7)
cello-user-dashboard  |     at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
cello-user-dashboard  |     at Object.onceWrapper (events.js:317:30)
cello-user-dashboard  | name: "AppWorkerDiedError"
cello-user-dashboard  | pid: 108
cello-user-dashboard  | hostname: cello-user-dashboard
cello-user-dashboard  | 
cello-user-dashboard  | 2020-02-26 02:45:19,545 ERROR 108 [master] app_worker#1:124 start fail, exiting with code:1
cello-user-dashboard  | 2020-02-26 02:45:19,549 ERROR 108 [master] exit with code:1
cello-user-dashboard  | 2020-02-26 02:45:19,555 ERROR 114 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
cello-user-dashboard  | ⚠️  Error: /node_modules/egg-bin/lib/start-cluster {"stricky":true,"port":8081,"baseDir":"/var/www","workers":1,"framework":"/var/www/node_modules/egg"} exit with code 1
cello-user-dashboard  | 2020-02-26 02:45:19,598 INFO 114 [agent_worker] beforeExit success
cello-user-dashboard  | 2020-02-26 02:45:19,599 ERROR 114 [agent_worker] exit with code:110
cello-user-dashboard  | ⚠️  Command Error, enable `DEBUG=common-bin` for detail
cello-user-dashboard  | npm ERR! code ELIFECYCLE
cello-user-dashboard  | npm ERR! errno 1
cello-user-dashboard  | npm ERR! user-dashboard@1.0.0 start:dev: `egg-bin dev --stricky --port 8081`
cello-user-dashboard  | npm ERR! Exit status 1
cello-user-dashboard  | npm ERR! 
cello-user-dashboard  | npm ERR! Failed at the user-dashboard@1.0.0 start:dev script.
cello-user-dashboard  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
cello-user-dashboard  | 
cello-user-dashboard  | npm ERR! A complete log of this run can be found in:
cello-user-dashboard  | npm ERR!     /root/.npm/_logs/2020-02-26T02_45_19_670Z-debug.log
cello-user-dashboard  | npm ERR! code ELIFECYCLE
cello-user-dashboard  | npm ERR! errno 1
cello-user-dashboard  | npm ERR! user-dashboard@1.0.0 start: `if-env NODE_ENV=production && npm run start:prod || npm run start:dev`
cello-user-dashboard  | npm ERR! Exit status 1
cello-user-dashboard  | npm ERR! 
cello-user-dashboard  | npm ERR! Failed at the user-dashboard@1.0.0 start script.
cello-user-dashboard  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
cello-user-dashboard  | 
cello-user-dashboard  | npm ERR! A complete log of this run can be found in:
cello-user-dashboard  | npm ERR!     /root/.npm/_logs/2020-02-26T02_45_19_722Z-debug.log

**Comment by xiegangqingnian** [comment]
是否 user这个镜像存在问题

**Comment by coderInk** [comment]
请问最后怎么解决的，我也遇到了这个问题
