### ISSUE TITLE
我改怎样新建代理

### ISSUE THREAD

**Issue by xiegangqingnian** [hyperledger/cello#113]
![image](https://user-images.githubusercontent.com/45548879/75408731-91b4f500-5951-11ea-97fc-5da21c59edd2.png)
新的代码版本中，8080于8081的两个登陆面板是否应该合并？

**Comment by xiegangqingnian** [comment]
创建个普通用户无法登陆的情况 与 未设置代理及节点有关吗？
![image](https://user-images.githubusercontent.com/45548879/75408806-d771bd80-5951-11ea-94c4-da41a37907e1.png)

**Comment by zhangjingwen2008** [comment]
same here.
