### ISSUE TITLE
Design the API spec for user dashboard

### ISSUE THREAD

**Issue by yeasy** [hyperledger/cello#118]
Need to re-arch the code following the [new governing model](https://docs.google.com/document/d/1Dw6cEKaul6FenORNkDcxvPDDKwpl0A5EmcJBlqAWJoU/edit#).

Feel free to review the [drafted spec](https://docs.google.com/document/d/129uzVcBzPspgNG7M1yaWMyJJ7Rz3YReScsNP2KYy568/edit#)

**Comment by dexhunter** [comment]
[Cello Agent API](https://docs.google.com/document/d/1XwkUORuySV2uDo1tl2e3SA3RPwrsKCoVplqmmKiK9N0/edit)

**Comment by yeasy** [comment]
> [Cello Agent API](https://docs.google.com/document/d/1XwkUORuySV2uDo1tl2e3SA3RPwrsKCoVplqmmKiK9N0/edit)

https://github.com/XuHugo/api-engine
