### ISSUE TITLE
PR broke CI

### ISSUE THREAD

**Issue by ryjones** [hyperledger/cello#125]
PR #120 was merged, and there are two repos that have not built since then:

https://hub.docker.com/repository/docker/hyperledger/cello-api-engine/builds
https://hub.docker.com/repository/docker/hyperledger/cello-dashboard/builds

**Comment by yeasy** [comment]
@ry, do you know the memory of the building env? It is said the building may fail with a less-than-1 GB memory server.

**Comment by ryjones** [comment]
The following dockerhub accounts have admin permissions:

- yeasy
- lordgoodman
- email4tong
- hightall

You can take a look in hub.docker.com at the settings and logs.

**Comment by ryjones** [comment]
The build for `cello-api-engine` is fixed. However, `cello-dashboard` is still failing. [Here are the errors right before the build fails](https://gist.github.com/ryjones/f701da075bb222b3448d7b41c9e257ca). I don't think this is actually a networking issue as it's been a persistent failure.

**Comment by ryjones** [comment]
@litong01 If you want to move all of this to Azure pipelines (all of the docker hub native stuff) I'll help
