### ISSUE TITLE
Move build onto Azure DevOps

### ISSUE THREAD

**Issue by litong01** [hyperledger/cello#138]
**Is your feature request related to a problem? Please describe.**
Docker Hub build is slow and limited. Linux Foundation has requested cello to move off of Docker Hub build
**Describe the solution you'd like**
Use Azure DevOps pipelines

**Describe alternatives you've considered**
This solution is what Hyperledger community wants, do not see any other options.

**Additional context**
None

**Comment by yeasy** [comment]
Duplicated and fixed in #140 .
