### ISSUE TITLE
improve download speed for cello in China

### ISSUE THREAD

**Issue by dexhunter** [hyperledger/cello#161]
Since I am located in mainland China right now, I want to share how to improve the download speed for cello users here. (Or you can set global proxy for your machine, which might be simpler)

## Docker Registry

change to
```
{
"registry-mirrors": [
"https://dockerhub.azk8s.cn",
"https://hub-mirror.c.163.com"
]
}
```

## Build Docker Images

The most time consuming thing here is install debian packages, it took forever. But simply using a mirror will speed up a lot. Add/Replace following lines in `build_image/common/`

For `api-engine`, use 
```Dockerfile
FROM python:3.6

# use tuna mirror
RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
# Install software
RUN apt-get update \
	&& apt-get install -y gettext-base graphviz libgraphviz-dev \
	&& apt-get autoclean \
	&& apt-get clean \
	&& apt-get autoremove && rm -rf /var/cache/apt/

# Set the working dir
WORKDIR /var/www/server

# Copy source code to the working dir
COPY src/api-engine ./

# Install python dependencies with tuna mirror
RUN	pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# Add uwsgi configuration file
COPY build_image/docker/common/api-engine/server.ini /etc/uwsgi/apps-enabled/

ENV RUN_MODE server

COPY build_image/docker/common/api-engine/entrypoint.sh /
CMD bash /entrypoint.sh
```

Two changes here, one for debian package installation, one for python package.

For `bashboard`,
add `RUN yarn config set registry https://registry.npm.taobao.org/` before `yarn run build`

For `nginx`,
add `RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list` similar to what we have done in `api-engine`

That's all, hope this helps for users located in mainland China.

**Comment by shuanzhao** [comment]
@dexhunter good job, save me lot of time, thanks so much.
