### ISSUE TITLE
Is this issue resolved? I am not even able to login. I get `请求错误 502: http://localhost:8081/api/token-verify

### ISSUE THREAD

**Issue by JerryGaoYJ** [hyperledger/cello#168]
Is this issue resolved? I am not even able to login. I get `请求错误 502: http://localhost:8081/api/token-verify
网关错误。`

_Originally posted by @cvhariharan in https://github.com/hyperledger/cello/issues/87#issuecomment-660600242_

**Comment by yeasy** [comment]
@haowenmvp met this issue, too.
@xichen1 suggest to wait till all containers are up.
