### ISSUE TITLE
why could Cello(release v0.9.0)only deploy Fabric on a single host?

### ISSUE THREAD

**Issue by dongge531** [hyperledger/cello#189]
## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

* OS:
* Architecture:
* Docker version:
* Docker compose version:
* Kubernetes version:

**Comment by yeasy** [comment]
In the ongoing 1.0.0, it will be resolved.

**Comment by mrchar** [comment]
@yeasy 请问1.0.0的新特性在哪里可以查看？ 是否支持分布式部署？有没有具体的发布时间呢？
