### ISSUE TITLE
Can not instantiate a go-ver chaincode

### ISSUE THREAD

**Issue by lyp830414** [hyperledger/cello#197]
## Expected Behavior

The go-ver chaincode should be instantiate in succeed.

## Current Behavior

Failure as I tried to instantiate a go-ver chaincode.

## Steps to Reproduce

1. Start the cello in branch release-0.9.0-h3c
2. Create the fabric network v1.4 (using DOCKER SWARM) under the operator dashboard.
3. Wait until the network bring up, then create the channel under the user dashboard
4. Upload my go-ver chaincode zip file (put the *.go into a directory, then package it into a zip file)
5. Click the instantiate chaincode under the chaincode page from user dashboard.
6. Then the issue happened, like following
    
![image](https://user-images.githubusercontent.com/13618985/101597414-a3bfda00-3a31-11eb-99ab-35a148d1b040.png)

## Context (Environment)

* OS:    Linux CentOS7-137 3.10.0-1160.6.1.el7.x86_64 
* Architecture:  x64
* Docker version:  docker 19.03.14
* Docker compose version:  docker-compose version 1.25.5, build 8a1c60f6
* Kubernetes version: (NULL)

**Comment by XuHugo** [comment]
You can display the log information of user dashboard。Which chaincode do you use，example02？You can display the initialization page, I want to see your parameters。

**Comment by lyp830414** [comment]
Yes, I uploaded fabric-samples-release-1.4's chaincode-->chaincode_example02-->go ver chancode onto the cello user dashboard. Here list more details about user dashboard.  (The key clue is that I did not use k8s for network model, but choosed the "docker" (docker swarm) on the cello operator to build my chain network)

Here's more deatils on my user dashboard.

![image](https://user-images.githubusercontent.com/13618985/102029155-599b7780-3de8-11eb-8a9b-407b1fc40544.png)

![image](https://user-images.githubusercontent.com/13618985/102029170-6ae48400-3de8-11eb-8279-069845b78638.png)

![image](https://user-images.githubusercontent.com/13618985/102029184-746dec00-3de8-11eb-89eb-6c7f8f02465b.png)

![image](https://user-images.githubusercontent.com/13618985/102029193-7afc6380-3de8-11eb-9afc-c5c123fca1d2.png)

![image](https://user-images.githubusercontent.com/13618985/102029201-8059ae00-3de8-11eb-8916-b7796b6d3abb.png)

![image](https://user-images.githubusercontent.com/13618985/102029213-89e31600-3de8-11eb-9636-0f6a9caf2921.png)

![image](https://user-images.githubusercontent.com/13618985/102029218-8cde0680-3de8-11eb-8524-f0c150d55ae0.png)

![image](https://user-images.githubusercontent.com/13618985/102029226-92d3e780-3de8-11eb-882a-130365cc248c.png)

![image](https://user-images.githubusercontent.com/13618985/102029515-aaf83680-3de9-11eb-8f30-171b3f29e298.png)

![image](https://user-images.githubusercontent.com/13618985/102029557-d844e480-3de9-11eb-9e86-cdcb7e52e470.png)

Here is the error content in above error message window.

请求错误 400: http://192.168.1.137:8081/v2/chaincodes/5fd0792f648e8d005cd0d5c7/instantiate
发出的请求有错误，服务器没有进行新建或修改数据的操作。

**Comment by lyp830414** [comment]
> You can display the log information of user dashboard。Which chaincode do you use，example02？You can display the initialization page, I want to see your parameters。



> You can display the log information of user dashboard。Which chaincode do you use，example02？You can display the initialization page, I want to see your parameters。

More information about:  
     What ever which chaincode I use with the go-ver chaincode ( any fabric-samples' chaincode with ver1.4 ), it always report the same error message, any no new vm-docker-container was created in the backend.  But as I used the java-ver chaincode to choose initialize chaincode, the java's vm-docker-container could be created, but it always stucked in step of initialized the chaincode step in the dashboard,  so I cannot see a record was made in the following graph. (But for now, I just want to find why go-ver chaincode could not be initialized under docker swarm network mode)
![image](https://user-images.githubusercontent.com/13618985/102029798-d6c7ec00-3dea-11eb-8626-8adf69028037.png)

I think that should be something wrong with cello platform, or anything wrong with my manual operation's sequences?

**Comment by lyp830414** [comment]
This issue was finally solved after try following 2 steps:
           1. I packaged the chaincode_example02.go into "chaincode_example02" folder and zip it. 
                     -- For  my previous operation, I put the chaincode_example02.go into different folder name: i.e:  folder named "test" 
           
          2. I used the wrong ccenv docker image with following clue:
                           a. I watched peer full docker logs and found this issue:
                           
![image](https://user-images.githubusercontent.com/13618985/102056836-f0d3ef80-3e27-11eb-808d-250fe91a83cc.png)
                           b.  Then I tried "docker pull hypderledger/fabric-ccenv:1.4.2"  and "docker tag  hypderledger/fabric-ccenv:1.4.2  hypderledger/fabric-ccenv:latest"
                             
         Elther wrong operation from 1 and 2 will lead that issue. Now my go-ver chaincode canbe intialized. 
         I will close this problem. thank you for reponse my issue anyway !  I'd may need your greatly help for my further cello problems.

**Comment by lyp830414** [comment]
This issue has been solved now.
