### ISSUE TITLE
部署完，运行报错

### ISSUE THREAD

**Issue by zhaochong** [hyperledger/cello#2]
部署完 cello 之后，监控 dashboard 日志：make logs service=dashboard，会有这样的报错：
dashbard      | Traceback (most recent call last):
dashbard      |   File "dashboard.py", line 4, in <module>
dashbard      |     from resources import bp_index, \
dashbard      |   File "/app/resources/__init__.py", line 1, in <module>
dashbard      |     from .index import bp_index
dashbard      |   File "/app/resources/index.py", line 17, in <module>
dashbard      |     from modules import cluster_handler, host_handler
dashbard      |   File "/app/modules/__init__.py", line 1, in <module>
dashbard      |     from .cluster import cluster_handler
dashbard      |   File "/app/modules/cluster.py", line 14, in <module>
dashbard      |     from agent import get_swarm_node_ip, \
dashbard      |   File "/app/agent/__init__.py", line 1, in <module>
dashbard      |     from .docker_swarm import get_project, \
dashbard      |   File "/app/agent/docker_swarm.py", line 10, in <module>
dashbard      |     from docker import Client
dashbard      | ImportError: cannot import name 'Client'

**Comment by yeasy** [comment]
We're using https://jira.hyperledger.org/ for issue tracking now.
Thanks!
