### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by Tanglumy** [hyperledger/cello#201]
It is my first time to use the cello and when I use the command: make start, the shell returns an error.(My Environment is MacOS X,The Big Sur)

**Comment by Tanglumy** [comment]
it seems that if you do not install the k8s, you can not use the command make start, and this error makes from the k8s

**Comment by XuHugo** [comment]
if you just execute make start，i think you need to install docker and docker-compose，which has nothing to do with k8s。

发自我的iPhone

**Comment by yeasy** [comment]
`release-0.9.0-h3c` is the latest stable release branch.
