### ISSUE TITLE
什么时候支持2.2

### ISSUE THREAD

**Issue by baigreen** [hyperledger/cello#204]
翘首以盼，实在不想重复造车轮。。

**Comment by mrchar** [comment]
为什么Fabric项目进展那么快，Cello项目进展却这么慢呢？说好的1.0更新，好久了都没出来。迫切需要1.0.0啊

**Comment by yeasy** [comment]
Due to the re-arch work, the 1.0 release is  delayed to support HLF v2.2.
For latest stable version, can try release-0.9.0-h3c branch.
