### ISSUE TITLE
无法新增节点

### ISSUE THREAD

**Issue by victorming** [hyperledger/cello#205]
Master部署以后，make start成功，但用admin/pass打开，无法新增节点：
![image](https://user-images.githubusercontent.com/3376709/104702020-62b59680-5750-11eb-9c74-aeeacf845cc0.png)

**Comment by victorming** [comment]
I changed to release-0.9.0-h3c and everything seems ok, but can't login the user-dashboard with 'admin/pass': 
![image](https://user-images.githubusercontent.com/3376709/104978720-7bb69400-5a3d-11eb-8c4a-00cd40cae9c5.png)
Anybody knows the correct password of admin?

**Comment by XuHugo** [comment]
user，you can find it in operator-dashboard
，password，666666。 

发自我的iPhone

**Comment by victorming** [comment]
There is only one user in operator-dashboard: admin, and I tried admin/666666 in user-dashboard but failed again:
![image](https://user-images.githubusercontent.com/3376709/105010934-4b8be700-5a77-11eb-86de-6ae5023b0b55.png)

**Comment by victorming** [comment]
I also encounted another issue during worker node setup: nfs failed to mount the master's directory:
![image](https://user-images.githubusercontent.com/3376709/105011277-bb9a6d00-5a77-11eb-9795-947e21e5223a.png)
I checked the master and found nfs-server failed because the default port was used. Can I skip the nfs service and start the fabric network?

**Comment by victorming** [comment]
I found the root cause for this error: there is a running service occupying the port 2049 which is the default port used by the nfs-server container. I killed the process and restart the master by 'make start'. Then all worker-node can connect to the master through nfs:
![image](https://user-images.githubusercontent.com/3376709/105133633-0d023500-5b28-11eb-8d40-3d2115e5a864.png)

**Comment by XuHugo** [comment]
you must use the user of your orgnization，such as，Admin@org1.h3c.com

发自我的iPhone

**Comment by victorming** [comment]
OK， I got it！Thank you.
