### ISSUE TITLE
have somebody use cello to manage fabric-gm?

### ISSUE THREAD

**Issue by csquan** [hyperledger/cello#213]
rt

**Comment by XuHugo** [comment]
may not,SDK does not support and some configurations。

**Comment by csquan** [comment]
how ablout replace nodejs-sdk to gm-sdk?what  configurations?

**Comment by XuHugo** [comment]
I suggest you pay attention here,https://github.com/Hyperledger-TWGC <https://github.com/Hyperledger-TWGC>；

**Comment by csquan** [comment]
I  had developed gm network already. 
I want use cello as baas.
so,must modify cello to make it manage gm-images,cello use nodejs-sdk and bin(configtxgen...),，how about  to replace it  ?
hava any ideas?

**Comment by csquan** [comment]
Hyperledger-TWGC  have no resource which I  needed.

**Comment by XuHugo** [comment]
1. Use gm of fabric tools to generate necessary files;
2. To replace fabric, you need to modify the startup files of peer and orderer;
3. Node JS SDK, this part of my work is not perfect, I can't give you good advice
