### ISSUE TITLE
Has the project stopped updating？

### ISSUE THREAD

**Issue by luolo-cry** [hyperledger/cello#220]
I noticed the CHANGELOG.md said the support latest fabric version is fabric1.x, its hard for me to deploy the fabric2 network. The cello last update is at 2018

**Comment by XuHugo** [comment]
Version 1.0 is under development. Welcome to join

**Comment by ivanv6** [comment]
Dear @XuHugo , when the version 1.0 will be released? Now cello supports Fabric 2.x? Thanks!

**Comment by yeasy** [comment]
1.0 is planed to release in 2021, and yes, it supports Fabric 2.x.
