### ISSUE TITLE
user Dashboard GUI

### ISSUE THREAD

**Issue by XuHugo** [hyperledger/cello#221]
**Is your feature request related to a problem? Please describe.**
Cello needs to provide a GUI for users。

**Describe the solution you'd like**
Users can deploy and operate fabric network through GUI

**Describe alternatives you've considered**

**Additional context**

**Comment by Lucas-gif845** [comment]
I am frustrated that the user dashboard container don't run properly with the error like 
![Screenshot from 2021-09-18 21-08-09](https://user-images.githubusercontent.com/59758895/133914556-c2493c05-62c2-49dd-8d6a-607581971943.png)
the operator dashboard is running ok.
