### ISSUE TITLE
 Network Types and SmartContract that Cello can support

### ISSUE THREAD

**Issue by mohjam2004** [hyperledger/cello#239]
Hi,
I want to know in what kind of block chain network the cello can work?
for example the besu can run in both permissioned and public networks and It can be run on the Ethereum public network or on private permissioned networks, as well as test networks such as Rinkeby, Ropsten, and Görli.

also I want to know what kind of smart contract can be run in cello?
for example in besu allows the deployment and execution of smart contracts via transactions within an Ethereum blockchain.

**Comment by XuHugo** [comment]
Cello currently only supports fabric
