### ISSUE TITLE
Not able to login with defualt username/password

### ISSUE THREAD

**Issue by ChrainWang** [hyperledger/cello#251]
I started the containers with following commands:
`make docker`
`make alldefconfig`
`make start`
localhost:8081 works but I am not able to login with `admin/pass`. The browser got 404 error for `/api/auth` and 400 error for `/api/verify-token`. I checked the log of cello-api-engine, it shows following warnings:
`/engine/auth Not Found `
`/engine/verify-token Bad Request`
What did I miss?

BTW, organization is required on the login page, what organization shall I use with default config.

**Comment by XuHugo** [comment]
This problem has been solved
