### ISSUE TITLE
User management of cello

### ISSUE THREAD

**Issue by XuHugo** [hyperledger/cello#268]
**Is your feature request related to a problem? Please describe.**
In Cello project, I hope to combine baas platform users with fabric users as much as possible.

**Describe the solution you'd like**
1、An organization can only register once. If it registers again, it will fail.
2、If we need to generate other users,  it is generated by registered users. 
3、At present, our users are divided into three categories: administrator, user and operator。
An administrator is the administrator of an organization. User is an ordinary member of the organization.
The operator is a super administrator who can control multiple organizations at the same time. He will appear in our centralized deployment.

administrator： It can handle everything in the organization。
user：Ordinary users can't deal with agent, network and user management。He is mainly used to deal with business-related issues.
operator： It can help alliance deal with organization, network, channel and other resources. But it can't deal with the specific business of the organization, so it can't deal with the chain code and user related resources.

**Describe alternatives you've considered**

**Additional context**

**Comment by yeasy** [comment]
Following HLF spec, would suggest:
* Admin's cert will have the "admin" ou.
* User's cert will have the "client" ou.
