### ISSUE TITLE
The dashboard is not perfect

### ISSUE THREAD

**Issue by XuHugo** [hyperledger/cello#269]
The dashboard is not perfect

## Expected Behavior
1、Basic operations of agent, network, user，node and organization, such as creation, deletion, modification, etc;
2、Add the organization operation item in the menu bar, because when we register the organization, we only record the organization in the database, and do not add nodes. We can add peer and orderer to the organization options at the same time.The node option is only used for viewing or expansion.
3、Modify the node option to add multiple nodes of different types at the same time;

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

* OS:
* Architecture:
* Docker version:
* Docker compose version:
* Kubernetes version:

**Comment by yeasy** [comment]
TODO:
* Remove organization from left;
* Add nodes in a batch
