### ISSUE TITLE
register api is 404

### ISSUE THREAD

**Issue by tglmm9377** [hyperledger/cello#280]
## Expected Behavior

when i use install with docker-compose from default mode ,docker running 
Creating cello-redis           ... done
Creating cello-postgres-server ... done
Creating cello-api-engine       ... done
Creating cello-api-engine-tasks ... done
Creating cello-nginx            ... done
Creating cello-dashboard        ... done
make[1]: Leaving directory '/opt/cello'

but in the dashboard i try to register a org ,it's response it's /api/v1/register is not found in console
![image](https://user-images.githubusercontent.com/43237551/127632634-d7a0d632-8e2f-473f-a590-aa14b7d1e151.png)

and  docker logs -f cello-dashboard has seem error

**Comment by yeasy** [comment]
Please try with the latest code after https://github.com/hyperledger/cello/pull/274.
