### ISSUE TITLE
login prompt 404

### ISSUE THREAD

**Issue by bingo789** [hyperledger/cello#295]
1. when i login,it prompt 404 not found: http://localhost:8081/api/v1/login
2. What does the organization fill in?
![a](https://user-images.githubusercontent.com/40812718/129685118-82cc3abc-1fbf-4a2f-93bf-62dbee1e5ab8.png)

**Comment by ukanhaupa** [comment]
I have the same issue.

**Comment by XuHugo** [comment]
org:  xq.cello.com

**Comment by Yinogi** [comment]
> 
> 
> you should register first。

i use register api and has the same issue (
![图片](https://user-images.githubusercontent.com/13634632/140040127-3d368c9d-6eb8-423c-bdda-233eb4eff136.png)

**Comment by PureBlack-lmh** [comment]
![image](https://user-images.githubusercontent.com/74767851/148154693-b7319ea4-3173-4320-a1da-c015b1253a47.png)
cello/src/dashboard/mock/user.js

@bingo789 @Yinogi

**Comment by Fu-XDU** [comment]
Same issue. Command below can change 404 to 400/401, I can not fix it
`SERVER_PUBLIC_IP={YourIP} CONFIG_PROD_MODE=y CONFIG_API_ENGINE_WEBROOT=/engine/v1 make start`
