### ISSUE TITLE
There is a risk of obtaining expired information

### ISSUE THREAD

**Issue by XuHugo** [hyperledger/cello#319]
https://github.com/hyperledger/cello/blob/3cb25eb7971e0e2ddc0aa363edf12bac240ab2af/src/api-engine/api/lib/peer/channel.py#L38

https://github.com/hyperledger/cello/blob/3cb25eb7971e0e2ddc0aa363edf12bac240ab2af/src/api-engine/api/lib/peer/channel.py#L127

If the file has already been created. Then an exception occurs, at which point the file is not deleted, and the next time the function is called, the information continues to be written to the file, causing the user to get an exception.

Perhaps using files is not a good method;

**Comment by tianxuanhong** [comment]
No,I has tested . even not delete the file never, will not get history information. Each execution overwrites the previous data。
>Output redirection: the contents of the original file will be overwritten 
> > append: the contents of the original file will not be overwritten, but appended to the end of the file
