### ISSUE TITLE
login and register api return 404

### ISSUE THREAD

**Issue by Yinogi** [hyperledger/cello#341]
i build my container with command:
make docker
CONFIG_PROD_MODE=y make start
and this is my container:
![图片](https://user-images.githubusercontent.com/13634632/140041533-bca228e3-cf37-4d84-ac82-890dfb80219e.png)

when i access localhost:8081, it returns token-verify 404 without do anything
![图片](https://user-images.githubusercontent.com/13634632/140041679-0543245e-507f-4856-b671-1005c4beb5a6.png)

and the same issue happend when using login and register
![图片](https://user-images.githubusercontent.com/13634632/140041949-6dca11d4-c9a1-4689-af4f-a573bcf47afb.png)

i do not know what happend on my system, is there any suggestion?

**Comment by Bearxhy123** [comment]
Is it resolved? I also encountered it, can you tell me how to solve it?

**Comment by Yinogi** [comment]
> 

not yet ( nobody reply

**Comment by Yinogi** [comment]
> Is it resolved? I also encountered it, can you tell me how to solve it?

not yet, nobody reply
