### ISSUE TITLE
Support for ARM architecture

### ISSUE THREAD

**Issue by grizzlyhackle** [hyperledger/cello#351]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 2rueSid** [comment]
Hey, @grizzlyhackle I've just set up cello on m1 chip running under rosetta.
You could simply hardcode these values in Makefile
```bash
ARCH   := x86_64
DOCKER_BASE_x86_64=x86_64/python:3.6
```
