### ISSUE TITLE
Can't run make start-dashboard target

### ISSUE THREAD

**Issue by kumar-shantanu** [hyperledger/cello#381]
Following the steps from GitHub but not able to start dashboard, it throws this error, 

###
make start-dashboard
make -C src/dashboard start;
make[1]: Entering directory '/home/ubuntu/cello/src/dashboard'
npm start

> cello-dashboard@1.0.0 start /home/ubuntu/cello/src/dashboard
> cross-env umi dev PORT=8001

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn umi ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm ERR! Linux 5.4.0-1060-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! cello-dashboard@1.0.0 start: `cross-env umi dev PORT=8001`
npm ERR! Exit status 1
###

## Expected Behavior

This should run the dashboard

## Current Behavior

Throws and error
## Steps to Reproduce

1. git clone <cello repository>
2. make api-engine 
3. make docker-rest-agent
4. make start
5. make start-dashboard

## Context (Environment)

* OS: Ubuntu 18.4 LTS
* Architecture:  x86_64
* Docker version:20.10.7
* Docker compose version: 1.29.2
* Kubernetes version:

## Detailed Description and log

The debug logs says,

####
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cello-dashboard@1.0.0~prestart: cello-dashboard@1.0.0
6 silly lifecycle cello-dashboard@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle cello-dashboard@1.0.0~start: cello-dashboard@1.0.0
8 verbose lifecycle cello-dashboard@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle cello-dashboard@1.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/ubuntu/cello/src/dashboard/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle cello-dashboard@1.0.0~start: CWD: /home/ubuntu/cello/src/dashboard
11 silly lifecycle cello-dashboard@1.0.0~start: Args: [ '-c', 'cross-env umi dev PORT=8001' ]
12 silly lifecycle cello-dashboard@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle cello-dashboard@1.0.0~start: Failed to exec start script
14 verbose stack Error: cello-dashboard@1.0.0 start: `cross-env umi dev PORT=8001`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid cello-dashboard@1.0.0
16 verbose cwd /home/ubuntu/cello/src/dashboard
17 error Linux 5.4.0-1060-aws
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error cello-dashboard@1.0.0 start: `cross-env umi dev PORT=8001`
22 error Exit status 1
23 error Failed at the cello-dashboard@1.0.0 start script 'cross-env umi dev PORT=8001'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the cello-dashboard package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env umi dev PORT=8001
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs cello-dashboard
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls cello-dashboard
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
####

**Comment by fengyangsy** [comment]
you can make dashboard image through "make dashboard",and start all container through "make start"
