### ISSUE TITLE
delete or update bug

### ISSUE THREAD

**Issue by pabcxyz** [hyperledger/cello#432]
![image](https://user-images.githubusercontent.com/8225375/162148168-482adb14-056d-46ec-b071-db4c2df9e562.png)
<img width="694" alt="image" src="https://user-images.githubusercontent.com/8225375/162148319-4e5d30d4-7c98-47b1-88c8-24206442f35f.png">

**Comment by Fu-XDU** [comment]
Same issue
<img width="624" alt="1" src="https://user-images.githubusercontent.com/49449864/163545400-b00c63cd-99d8-410f-acde-d9ce92151d53.png">
<img width="340" alt="2" src="https://user-images.githubusercontent.com/49449864/163545424-73cd03d2-de66-4882-8cf4-fb8fe18ae644.png">
<img width="344" alt="3" src="https://user-images.githubusercontent.com/49449864/163545432-9c5e0821-93e5-48d0-bdad-f192752fd37f.png">
