### ISSUE TITLE
急！急！急：cello中设置kubernetes类型的代理地址的问题

### ISSUE THREAD

**Issue by aesirteam** [hyperledger/cello#445]
![2022-05-17 18-35-35 的屏幕截图](https://user-images.githubusercontent.com/5821532/168792292-4e7bbbc9-331c-4326-a0b8-20fb99f77c99.png)

**哪位大神做过类似集成？請不靈賜教！**

运行make docker后生成鏡像：
hyperledger/cello-api-engine
hyperledger/cello-nginx
hyperledger/cello-dashboard
hyperledger/cello-agent-kubernetes
並在k8s cluster中部署運行，api_engine接口調用正常！
![2022-05-17 18-43-03 的屏幕截图](https://user-images.githubusercontent.com/5821532/168793535-d86bee03-402c-420b-86ce-61cade24976a.png)

**Comment by fengyangsy** [comment]
现在版本的cello还没有支持kubernetes
