### ISSUE TITLE
peer and order and ca Unable to run

### ISSUE THREAD

**Issue by Tpsilence** [hyperledger/cello#453]
After the network is created, the active host disappears, and the peer and Order nodes cannot run.Does anyone know why？
<img width="757" alt="微信截图_20220602152005" src="https://user-images.githubusercontent.com/98136624/171575432-7f9ad3c4-6917-49c3-8cd4-2bfe0dab89f5.png">
<img width="757" alt="host" src="https://user-images.githubusercontent.com/98136624/171570685-43845d6d-1901-41ac-be26-373ca92724b6.png">
<img width="757" alt="docker" src="https://user-images.githubusercontent.com/98136624/171570604-cdc24d08-2262-4eb1-b7f6-8a14ec2ffcad.png">

**Comment by fengyangsy** [comment]
do you mount the agent path to cello host? if not mount ,you can use this command "mount -t nfs -o vers=4,loud 192.168.0.62:/ /opt/cello", send to agent host, the ip is the cello host
