### ISSUE TITLE
Support both v1 and v2 of docker compose 

### ISSUE THREAD

**Issue by xichen1** [hyperledger/cello#460]
Currently, the project only supports docker compose v1 `docker-compose`, while there exists v2 `docker compose`. Based on this [answer](https://stackoverflow.com/a/66516826), v1 has now been deprecated and most new docker users are using v2.

The users of v2 on Linux may get the following error message when running `make start`:
```bash
docker-compose -f bootup/docker-compose-files/docker-compose-dev.yml up -d --force-recreate --remove-orphans
make[1]: docker-compose: Command not found
make[1]: *** [Makefile:215: start-docker-compose] Error 127
```

The Makefile can be changed to support both versions of docker compose.

**Comment by yeasy** [comment]
Let's switch to v2 version.
