### ISSUE TITLE
docker compose -f   报错  unknown shorthand flag: 'f' in -f

### ISSUE THREAD

**Issue by 499909744** [hyperledger/cello#473]
docker-compose 版本 2.6.4  
修改Makefile ，docker compose 改为 docker-compose后是正常的

**Comment by zhuyuanmao** [comment]
@xichen1 Can you have a look at this issue, please?

**Comment by xichen1** [comment]
请问具体是运行了哪个make命令后报错？还是说所有命令都有问题？

**Comment by xichen1** [comment]
根据[这个文档](https://docs.docker.com/compose/release-notes/#261)，最新的docker compose版本是2.61。
能不能看一下`docker-compose version`和`docker compose version`分别会返回什么？

**Comment by 499909744** [comment]
[root@centos cello]# docker-compose version
Docker Compose version v2.6.1
[root@centos cello]# docker compose version
docker: 'compose' is not a docker command.
See 'docker --help'

**Comment by 499909744** [comment]
[root@centos cello]# docker version
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:11 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:29 2022
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by 499909744** [comment]
https://labs.play-with-docker.com/  这个环境里边 docker compose version 是可以的；docker version 详情中的 GitCommit: v1.1.2-0-ga916309 是不一样的

**Comment by 499909744** [comment]
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh   按照官方指定的命令安装一次docker后就可以了;应该是docker缺少docker-compose-plugin插件
