### ISSUE TITLE
Operating nodes returns "error": "invalid operation"

### ISSUE THREAD

**Issue by xichen1** [hyperledger/cello#477]
When I used Postman to test operating nodes, it returns the following response, and the status of the node didn't change (I used the operations: start, stop and restart and they all gave the same result.)
```
{
    "data": {
        "error": "invalid operation"
    },
    "msg": null,
    "status": "successful"
}
```
From the code here, it seems we can only operate the node when its status is `paused` or `running`
https://github.com/hyperledger/cello/blob/c9f538b17922e9dade7f56f3155ea4e7801a7517/src/api-engine/api/routes/node/views.py#L499-L517

However, the node status is `created` by default
https://github.com/hyperledger/cello/blob/c9f538b17922e9dade7f56f3155ea4e7801a7517/src/api-engine/api/models.py#L521-L526

Did I miss any API which can change nodes' status?

**Comment by yeasy** [comment]
created should be able to start to running.
I would suggest after creating node from console, directly start it. a.k.a., no intermediate created status.

**Comment by xichen1** [comment]
Fixed by creating `/opt/hyperledger` folder
