### ISSUE TITLE
Failed to stop a running node

### ISSUE THREAD

**Issue by xichen1** [hyperledger/cello#480]
## Expected Behavior
A running node should be stopped after clicking the stop button.

## Current Behavior
Error occurs, failed to stop the node

## Possible Solution
The backend to operate on a node requires a payload to specify the action, but the frontend didn't call it with the payload.
Instead, it used the URL parameter to specify the action.

![fail](https://user-images.githubusercontent.com/47851834/184304105-9e2a6b5e-09a7-4789-bba8-80fed0c4fee9.PNG)
![payload](https://user-images.githubusercontent.com/47851834/184304132-7be889b9-be48-4a3d-b9a2-48f48212c6eb.PNG)
![response](https://user-images.githubusercontent.com/47851834/184304356-26fcf044-c7d4-4a6d-bdfb-93e3c8db43e2.png)

## Steps to Reproduce
1. login
2. create agent, network
3. create node and make sure it's running
4. stop the node

## Possible Implementation
Make the frontend pass the action in the payload.

**Comment by yeasy** [comment]
Discussed with @fengyangsy , should use payload.
