### ISSUE TITLE
The dockerfile of kubernetes agent need to revise to support corev1api of kubernetes

### ISSUE THREAD

**Issue by ritel126** [hyperledger/cello#49]
The dockerfile of kubernetes agent need to revise to support corev1api of kubernetes

## Expected Behavior

when we create node,error will report like this:

# #_root@rtxie-Standard-PC-i440FX-PIIX-1996:~/cello# docker logs4834991f2f59
docker: 'logs4834991f2f59' is not a docker command.
See 'docker --help'
root@rtxie-Standard-PC-i440FX-PIIX-1996:~/cello# docker logs 4834991f2f59
Exception when call CoreV1Api: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Wed, 23 Oct 2019 03:37:38 GMT', 'Content-Length': '264'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"service-23be5dac-6ef5-4282-92f9-5e36781c16de\" not found","reason":"NotFound","details":{"name":"service-23be5dac-6ef5-4282-92f9-5e36781c16de","kind":"services"},"code":404}

Exception when call AppsV1beta1Api: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Wed, 23 Oct 2019 03:37:38 GMT', 'Content-Length': '361'})
HTTP response body: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "deployments.extensions \"deploy-23be5dac-6ef5-4282-92f9-5e36781c16de\" not found",
  "reason": "NotFound",
  "details": {
    "name": "deploy-23be5dac-6ef5-4282-92f9-5e36781c16de",
    "group": "extensions",
    "kind": "deployments"
  },
  "code": 404
}_

## Steps to Reproduce

1.
2.
3.
4.

## Possible Implementation

The dockerfile need to revise like this

**ENV KUBECONFIG /app/.kube/config
CMD export PYTHON_VER=${PYTHON_VERSION:0:3}
ENV PYTHONPATH /app:/usr/local/lib/python${PYTHON_VER}:/usr/local/lib/python${PTYHON_VER}/lib-dynload:/usr/local/lib/python${PATHON_VER}/site-packages**

**Comment by hightall** [comment]
@ritel126 Add these path into PYTHONPATH is fine, but I think it's not the root cause of corev1Api not found. you still can add this env variable.
