### ISSUE TITLE
Macbook M1 Support Issue after Updating makefile

### ISSUE THREAD

**Issue by xichen1** [hyperledger/cello#521]
After using the new makefile to build api-engine, network cannot be created using frontend API call and an error arises `qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory` in api-engine container.

It seems related to the updated makefile in #519. 
In the old makefile, the platform for arm64 arch was `linux/amd64` in line [319](https://github.com/hyperledger/cello/pull/519/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L319). 
In the updated makefile, the platform is `linux/$(ARCH)` in line [214](https://github.com/hyperledger/cello/pull/519/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R214).

As the `$(ARCH)` value is `arm64` in m1 OS, it is different from the old `amd64` platform. It seems someone also had this issue, and it was solved by using `linux/amd64` for m1 arch. [Source](https://stackoverflow.com/questions/71040681/qemu-x86-64-could-not-open-lib64-ld-linux-x86-64-so-2-no-such-file-or-direc)

Update: I manually changed the platform value to `linux/amd64` on m1 and network can be created without error.

**Comment by yeasy** [comment]
Good catch, would you like to help make a PR for it?

**Comment by xichen1** [comment]
Sure, #522 is created to fix it. And it has been tested and works well.
