### ISSUE TITLE
build(makefile): commander@11.0.0: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.17.6"

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cello#528]
I cloned the project, installed the dependencies as per the docs and then did `make local` and it crashed.

## Expected Behavior

Quick start steps work.

## Current Behavior

It crashes with the error from the issue title.
[2023-06-15-hyperledger-cello-make-local-crash.log](https://github.com/hyperledger/cello/files/11765847/2023-06-15-hyperledger-cello-make-local-crash.log)

## Possible Solution

Probably either pass in the [--ignore-engines](https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-engines) flag or use a different version so that it's compatible.

## Steps to Reproduce
1. git clone
2. `make local`
3. profit

## Context (Environment)

* OS: `Ubuntu 22.04.2 LTS`
* Architecture: amd64
* Docker version: `Docker version 24.0.2, build cb74dfc`
* Docker compose version: `Docker version 24.0.2, build cb74dfc`
* Kubernetes version: N/A

## Detailed Description and log

[2023-06-15-hyperledger-cello-make-local-crash.log](https://github.com/hyperledger/cello/files/11765858/2023-06-15-hyperledger-cello-make-local-crash.log)

## Possible Implementation

Same as "possible solution" above.

**Comment by yeasy** [comment]
#0 59.38 error commander@11.0.0: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.17.6"

**Comment by xichen1** [comment]
It appears that the problem originated from the dependency `"mockjs": "^1.0.1-beta3"` in the project. 

The issue arises since mockjs use `"commander": "*"` as their dependency, which installs the latest version of commander. See [their package.json file](https://github.com/nuysoft/Mock/blob/00ce04b92eb464e664a4438430903f2de96efb47/package.json#L14). We may need to find a way to override the commander's version.

**Comment by petermetz** [comment]
> It appears that the problem originated from the dependency `"mockjs": "^1.0.1-beta3"` in the project.
> 
> The issue arises since mockjs use `"commander": "*"` as their dependency, which installs the latest version of commander. See [their package.json file](https://github.com/nuysoft/Mock/blob/00ce04b92eb464e664a4438430903f2de96efb47/package.json#L14). We may need to find a way to override the commander's version.

@xichen1 Please take a look at these links for the recommended way of overriding transitive dependency versions (usually necessary for security upgrades but this is also an applicable use-case IMO)

**yarn** https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/
**npm** https://stackoverflow.com/questions/52416312/npm-equivalent-of-yarn-resolutions
