### ISSUE TITLE
Frontend code style check failed

### ISSUE THREAD

**Issue by xichen1** [hyperledger/cello#536]
One recent CI failed: [#143](https://github.com/hyperledger/cello/actions/runs/5661730955)

## Expected Behavior
All code check CI shoud pass.

## Current Behavior
One CI failed, some code styles don't meet standards. 

## Possible Solution
Unnecessary curly braces found [here](https://github.com/hyperledger/cello/actions/runs/5661730955/job/15340256775#step:5:1732). Should be a easy fix.

## Steps to Reproduce

1. Run `make check` locally and code style check will fail.

**Comment by xiaor2** [comment]
I will work on this. I tried to run `make check` and got this error message. Do you know how to resolve this? Thanks.
![image](https://github.com/hyperledger/cello/assets/80271418/b4081a11-fb2d-401d-9ee1-9a9846a32cb1)

**Comment by xichen1** [comment]
The `make check` script uses a python tool `tox` and it seems your machine doesn't have it installed. 
Please follow this [page](https://tox.wiki/en/latest/installation.html), install the `tox` on your machine and try again.

**Comment by xiaor2** [comment]
Thanks! I have resolved this issue. But there is another issue. 
I have installed the bzip2 on my WSL, but it still got this error.
![image](https://github.com/hyperledger/cello/assets/80271418/8be65d53-aa42-4b48-8ae9-db973080d414)

**Comment by xichen1** [comment]
This is not related to the WSL since it's running in a docker container. Each container has a separate environment and that's different from your host machine. So installing bzip2 on your own WSL won't solve the issue

In the past CIs, the error wasn't found because it seems not to affect the final result. For example in [Github Action #140](https://github.com/hyperledger/cello/actions/runs/5420027719/job/14677925059#step:5:1575), it showed the same error but the whole CI still passed.

Regarding the solution, the issue is sourced from the node image used for a style check. It seems the node image we are using now has some internal issues. 
I made an experiment [here](https://github.com/xichen1/cello/actions/runs/5798315782/job/15715775845#step:5:1670) by upgrading node version to `node:14.17` and no such error anymore.  Currently `node:12.6.0-slim` was used for code sytle checking and `node:14.17` was for the dashboard production. So I suggest that we can upgrade code check image to 14.17 in order to match the production and to avoid such issues. 

My experiment commits: https://github.com/xichen1/cello/pull/3/files

What do you think? @yeasy @fengyangsy @zhuyuanmao

**Comment by zhuyuanmao** [comment]
> This is not related to the WSL since it's running in a docker container. Each container has a separate environment and that's different from your host machine. So installing bzip2 on your own WSL won't solve the issue
> 
> In the past CIs, the error wasn't found because it seems not to affect the final result. For example in [Github Action #140](https://github.com/hyperledger/cello/actions/runs/5420027719/job/14677925059#step:5:1575), it showed the same error but the whole CI still passed.
> 
> Regarding the solution, the issue is sourced from the node image used for a style check. It seems the node image we are using now has some internal issues. I made an experiment [here](https://github.com/xichen1/cello/pull/3/files) by upgrading node version to `node:14.17` and no such error anymore([related CI](https://github.com/xichen1/cello/actions/runs/5798315782/job/15715775845#step:5:1543)). Currently `node:12.6.0-slim` was used for code sytle checking and `node:14.17` was for the dashboard production. So I suggest that we can upgrade code check image to 14.17 in order to match the production and to avoid such issues.
> 
> What do you think? @yeasy @fengyangsy @zhuyuanmao

+1 for using 14.17 instead

**Comment by yeasy** [comment]
+1!

**Comment by xichen1** [comment]
Fixed in #538
