### ISSUE TITLE
account can't log in

### ISSUE THREAD

**Issue by haowenmvp** [hyperledger/cello#545]
account can't log in 
It's the same with #168 ,  but I didn't find solution for it. 
![image](https://github.com/hyperledger/cello/assets/35884515/7df0c6b7-c478-4ea2-824f-5ff1f609c459)

## Possible Solution

reconnect with database

## Context (Environment)

* OS: mac os 
* Architecture:m1
* Docker version: 4.21.1 (114176)
* Docker compose version:v2.19.1
* Kubernetes version:v1.27.2

## Detailed Description and log

It seems like it is database connection error
![image](https://github.com/hyperledger/cello/assets/35884515/6eecab12-feff-476d-9ea7-5c8be900cfdc)
![image](https://github.com/hyperledger/cello/assets/35884515/357f212a-adb6-4cc6-bdb3-b15ad98fb7f5)

**Comment by zhuyuanmao** [comment]
looks like the issue is caused by the db not being initialization when api-engine tried to connect it, can you confirm if the `cello-postgres` container is running?

**Comment by haowenmvp** [comment]
I think it is running
![image](https://github.com/hyperledger/cello/assets/35884515/cee9cbd8-2db4-4a21-b9c1-c2eafb51d189)

**Comment by haowenmvp** [comment]
@zhuyuanmao told me to shut down and restart api-engine container and it worked.
