### ISSUE TITLE
Not working，Many functions have a 400 status code

### ISSUE THREAD

**Issue by 0verf1ow** [hyperledger/cello#592]
I used the v1.0 release version of the main branch
![image](https://github.com/hyperledger/cello/assets/62374498/de3c4ea9-93c2-4ea2-802e-9dcc002018c2)
When I started the service and logged into the web system, many functions had 400 status codes, which prevented me from using them
![image](https://github.com/hyperledger/cello/assets/62374498/207b6695-81ad-4a5c-bad6-b0b744b11faa)
![image](https://github.com/hyperledger/cello/assets/62374498/00135f99-0301-43e4-a08e-8ffce351fc20)
![image](https://github.com/hyperledger/cello/assets/62374498/33a268fd-ac49-4102-8a8f-76e23be017b7)

**Comment by xichen1** [comment]
Could you clean the local build first by running `make clean`, then pull the lastest main branch and try it again? Our database model and code base have changed since v1.0 and the inconsistency may cause the issue.

Based on your screenshot, for the ca node creation error, it may be because you haven't created the agent yet. Please use  `http://cello.docker.agent:5001` as the agent URL, as it will connect Cello to the docker network.

For the Network and chaincode GET issues, please try to pull the latest version and try again. 

We will enhance our documentation in the next release, thank you for your patience.

**Comment by wibin86** [comment]
![image](https://github.com/hyperledger/cello/assets/17491154/93ed411f-5209-48b9-88a4-b3af2a2e6d7e)
you need set the agent first，then add the node

**Comment by 0verf1ow** [comment]
> 您可以先通过运行清理本地构建`make clean`，然后拉出最新的主分支并重试吗？自 v1.0 以来，我们的数据库模型和代码库已发生变化，不一致可能会导致问题。
> 
> 根据您的截图，对于ca节点创建错误，可能是因为您还没有创建代理。请使用 `http://cello.docker.agent:5001`作为代理 URL，因为它将把 Cello 连接到 docker 网络。如果您愿意，您可以向我们提供错误消息或 docker 日志，以便我们进一步调查。
> 
> 对于网络和链码 GET 问题，请尝试拉取最新版本并重试。
> 
> 我们将在下一个版本中增强我们的文档，感谢您的耐心等待。

The latest version also has the same problem. I tried many versions but can't run this project. It's really too bad.

**Comment by 0verf1ow** [comment]
Note that I am using the latest version
Creating a proxy also reported an error
![image](https://github.com/hyperledger/cello/assets/62374498/b80e1a3a-fe1e-42d1-b106-0813ede3098b)
Except for creating a user, it is normal, and other api requests will have a 400 status code.

**Comment by xichen1** [comment]
> Note that I am using the latest version Creating a proxy also reported an error ![image](https://private-user-images.githubusercontent.com/62374498/297659477-b80e1a3a-fe1e-42d1-b106-0813ede3098b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjY0OTcsIm5iZiI6MTcwNTU2NjE5NywicGF0aCI6Ii82MjM3NDQ5OC8yOTc2NTk0NzctYjgwZTFhM2EtZmUxZS00MmQxLWIxMDYtMDgxM2VkZTMwOThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ODU5MWNmMGZlYTcwMzFkY2U5ODhkMWMwYTBiN2JjMDM0YzUwYmI4ZGM2ZWJkZWNkMmUxOGIwZmY3OTBhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bbqg4xTWhn9r5OT_ErbOEnfF1jW1pj3xGUJTs2-_4ak) Except for creating a user, it is normal, and other api requests will have a 400 status code.

Could you check if there are any error messages in docker containers? The log may help us find the issue.

**Comment by 0verf1ow** [comment]
> > Note that I am using the latest version Creating a proxy also reported an error ![image](https://private-user-images.githubusercontent.com/62374498/297659477-b80e1a3a-fe1e-42d1-b106-0813ede3098b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NjY0OTcsIm5iZiI6MTcwNTU2NjE5NywicGF0aCI6Ii82MjM3NDQ5OC8yOTc2NTk0NzctYjgwZTFhM2EtZmUxZS00MmQxLWIxMDYtMDgxM2VkZTMwOThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA4MjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ODU5MWNmMGZlYTcwMzFkY2U5ODhkMWMwYTBiN2JjMDM0YzUwYmI4ZGM2ZWJkZWNkMmUxOGIwZmY3OTBhMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bbqg4xTWhn9r5OT_ErbOEnfF1jW1pj3xGUJTs2-_4ak) Except for creating a user, it is normal, and other api requests will have a 400 status code.
> 
> Could you check if there are any error messages in docker containers? The log may help us find the issue.

Where are the logs of the mirror hyperledger/cello-api-engine api container stored?

**Comment by 0verf1ow** [comment]
1. Add the organization http package information
![image](https://github.com/hyperledger/cello/assets/62374498/2e2b5ec8-d901-4a4f-a252-b034dc6c82fd)
2. Add Agent http package information
![image](https://github.com/hyperledger/cello/assets/62374498/7f54f9bb-070a-48d0-ac1a-6c9abb5b66b8)
3. Add network http package information
![image](https://github.com/hyperledger/cello/assets/62374498/d4b28526-b651-41da-84b5-eb4ea7b47f8b)
.....
But adding users is possible
![image](https://github.com/hyperledger/cello/assets/62374498/1ffd72da-4e2b-43d6-8d77-8bdd2e5f41c1)

**Comment by yeasy** [comment]
@YUNGU23 will add the steps later.

**Comment by YUNGU23** [comment]
Hi 0verf1ow, thank you for your issue. I tried to address your issue, but each time it works well. 

Here is my step by step process, hope it helps:

1. Update to the latest version;
2. make local -> make docker -> make start
3. Open the web link and log in: http://localhost:8081/
4. It works well, and don't have any issue

![image](https://github.com/hyperledger/cello/assets/123411769/3949434e-430e-42b2-8fea-f46cfb2cd555)
![image](https://github.com/hyperledger/cello/assets/123411769/687f8fae-2793-42cd-8ab8-42d8183aec83)
![image](https://github.com/hyperledger/cello/assets/123411769/ca8a7394-47c2-4294-8734-70f2847321a3)
![image](https://github.com/hyperledger/cello/assets/123411769/575b7d4b-f1da-437a-b40d-2dceb0ffb623)

**Comment by Rushi-Kumar** [comment]
@YUNGU23  Were you able to upload the chaincode? Please help me with the stated issue #598
