### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by xichen1** [hyperledger/cello#634]
Per the report reviewer's [comment](https://github.com/hyperledger/toc/pull/295#discussion_r1750908238), we could refine/create the roadmap for the project

**Comment by yeasy** [comment]
+1!
recent items include:
* upgrade to HLF v2.5;
* chaincode operation.

**Comment by xichen1** [comment]
Fixing the existing testing cases and adding more testing might be an option. I feel it's hard to check the system's overall health after changing some code. Some regression testing with auto CI/CD check might be helpful.

**Comment by xichen1** [comment]
I created a very simple draft for the roadmap [here](https://wiki.hyperledger.org/display/cello/Hyperledger+Cello+Roadmap)

**Comment by yeasy** [comment]
> I created a very simple draft for the roadmap [here](https://wiki.hyperledger.org/display/cello/Hyperledger+Cello+Roadmap)

Let's move it to github wiki, since the confluence page will be deprecated.

**Comment by xichen1** [comment]
Created at [Github wiki](https://github.com/hyperledger/cello/wiki/Project-Roadmap)
