### ISSUE TITLE
Optimize container creation for node

### ISSUE THREAD

**Issue by YoungHypo** [hyperledger/cello#658]
The function of "def _conversion_msp_tls_cfg(self, type, org, node)" from [node/views.py](https://github.com/hyperledger/cello/blob/main/src/api-engine/api/routes/node/views.py) is compress/zip important files or certificates such as node's msp, tls, etc., and pass them in for decompression/unzip when creating containers

This operation can be optimized to eliminate the compression and decompression process
 
For the function of "def create_node()" from [agent/docker-test-agent/server.py](https://github.com/hyperledger/cello/blob/main/src/agent/docker-rest-agent/server.py), We can modify the mapping relationship of the container's volumes so that the container maps to a local file about the node.

for example,
```python
volumes = [
    'LOCAL_NODE_FILE': /opt/cello/fabric
]
```

**Comment by yeasy** [comment]
The api-engine and agent may exist in different hosts.
