### ISSUE TITLE
Broken/Missing Setup Doc Links

### ISSUE THREAD

**Issue by ghost** [hyperledger/cello#68]
Setup Doc links are not available or there are broken links

## Expected Behavior
User should be able to navigate to the doc links

## Current Behavior
User is not able to navigate to the doc links due to broken links or unavailable links

## Possible Solution
Please update the doc links

## Steps to Reproduce
Navigate to 
1. https://github.com/hyperledger/cello/blob/master/docs/tutorial.md
2. https://github.com/hyperledger/cello/blob/master/docs/setup/server.md#21-clone-source-code
3. https://github.com/hyperledger/cello/blob/master/docs/setup/server.md#22-prepare-environment
4. https://github.com/hyperledger/cello/blob/master/docs/setup/server.md#23-start-service

**Comment by Roshan13046** [comment]
I would like to fix this issue. Can I go ahead?
