### ISSUE TITLE
no 8080 port

### ISSUE THREAD

**Issue by Ywmet** [hyperledger/cello#87]
When I run make setup-master,setup-worker and make run.

![E3389BD7-7CD3-46BA-A00D-A241B75097D9](https://user-images.githubusercontent.com/6890141/71607526-1505d480-2bb5-11ea-86f2-10e78e621bb6.png)

How to proceed like docs

**Comment by seVereUnemployment** [comment]
Same issue here.

**Comment by flyingbird2017** [comment]
yeah, I have to same problems like you.

**Comment by perfectjoey** [comment]
I have the same problem, it seems like that there are no good document for this project, about how to add the agent, and how to set the master node and work node for the latest codes.

**Comment by perfectjoey** [comment]
any update for this?

**Comment by neutralsecond** [comment]
@perfectjoey  Seems like documentation was out of date. Currently a single login page at port 8081 is used both for admin and users.

**Comment by xiegangqingnian** [comment]
> @perfectjoey 似乎文档已过时。当前，端口8081上的单个登录页面同时用于管理员和用户。

你好，请问你的用户登陆页面可以正常打开吗

**Comment by musarona** [comment]
> > @perfectjoey 似乎文档已过时。当前，端口8081上的单个登录页面同时用于管理员和用户。
> 
> 你好，请问你的用户登陆页面可以正常打开吗
可以登录，但admin登录后没有相应的功能。

**Comment by silentvolcano** [comment]
8081不能登录，出现错误提示。

**Comment by xoco70** [comment]
It happens to me too, I can login with admin / pass, but then I can't do anything, system always says I am not connected :(

**Comment by cvhariharan** [comment]
Is this issue resolved? I am not even able to login. I get `请求错误 502: http://localhost:8081/api/token-verify
网关错误。`

**Comment by dexhunter** [comment]
The 8081 port works but I got the following errors sometimes:

![image](https://user-images.githubusercontent.com/6930518/88446317-9d064100-ce5b-11ea-8eee-947363379618.png)
